github: [plaintextaccounting, simonmichael]  # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ["https://FUPRK2ja1JWAeGBs5oLCRUTLo9Ve8jXcWL1Lcyoa4vi4, "https://www.solonaadress.com/donate/?"]
